# fly.toml - Configuration for AI Interview Platform WebRTC SDP Proxy
app = "interview-sdp-proxy"
primary_region = "mia"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  LOG_LEVEL = "info"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "3s"
    method = "GET"
    path = "/healthz"

[metrics]
  port = 9091
  path = "/metrics"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  
[mounts]
  destination = "/data"
  source = "interview_app_data"

# Scale to zero when idle
[experimental]
  auto_rollback = true
  kill_signal = "SIGINT"
  kill_timeout = "5s"
  
# Enable WebSockets
[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true 